### ISSUE TITLE
Consider renaming

### ISSUE THREAD

**Issue by fredemmott** [appertly/hcollection#1]
https://github.com/phplang/phack

**Comment by fredemmott** [comment]
Also, H2TP probably contains some of what you're looking for

**Comment by doublecompile** [comment]
Ah! I just did a precursory search on Packagist for "phack", finding nothing. Can do. 

As for H2TP, this project is really meant for teams in transition, both to and from Hack (really, primarily, a PHP project looking to update their API before they move to HHVM, and also a Hack project looking to move to PHP).

Thanks for the note about the phack project. I may look to contribute there.

**Comment by fredemmott** [comment]
Yep, I realize they have different goals - however, H2TP does include a PHP implementation of Hack collections

**Comment by doublecompile** [comment]
Heh. Actually, I was looking at it as a starting point, until I ran into this puppy: facebook/hhvm#7660

I may still change to BSD license, fork those files, and heavily massage them. Either way, you'll find out soon enough. :+1: Thanks for the second pair of eyes, Fred.

**Comment by fredemmott** [comment]
also cc @jesseschalken
